// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLNXs6UjW9To6RrSyw278K0fAHEPx7IF4',
    appId: '1:372707738831:web:9deaf340e7813b137323ba',
    messagingSenderId: '372707738831',
    projectId: 'payfx-global',
    authDomain: 'payfx-global.firebaseapp.com',
    storageBucket: 'payfx-global.firebasestorage.app',
    measurementId: 'G-GXHRD17N7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGMyi6fujHV45DNZ8UcaPvmcjQuxXfIuo',
    appId: '1:372707738831:android:cedee25b785629627323ba',
    messagingSenderId: '372707738831',
    projectId: 'payfx-global',
    storageBucket: 'payfx-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqZZTHsCnDX1Kjxq1adpuuJFqq4hZVIQ',
    appId: '1:372707738831:ios:3c84eb568ba5c8147323ba',
    messagingSenderId: '372707738831',
    projectId: 'payfx-global',
    storageBucket: 'payfx-global.firebasestorage.app',
    iosBundleId: 'com.payfx.payfxglobalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqZZTHsCnDX1Kjxq1adpuuJFqq4hZVIQ',
    appId: '1:372707738831:ios:68288604673134437323ba',
    messagingSenderId: '372707738831',
    projectId: 'payfx-global',
    storageBucket: 'payfx-global.firebasestorage.app',
    iosBundleId: 'com.payfx.payfxglobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLNXs6UjW9To6RrSyw278K0fAHEPx7IF4',
    appId: '1:372707738831:web:82e7f6b011012e557323ba',
    messagingSenderId: '372707738831',
    projectId: 'payfx-global',
    authDomain: 'payfx-global.firebaseapp.com',
    storageBucket: 'payfx-global.firebasestorage.app',
    measurementId: 'G-WC8H89GVQ8',
  );
}